# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: 
      - "main" 
      - feature/frontend
  pull_request:
    branches: [ "main" ]

jobs:
    
  version:
    runs-on: ubuntu-latest
    outputs:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
  
  backend:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: cd flight-status-backend && mvn -B package --file pom.xml
    
    
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/jfwenisch/flightstatus-backend

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: flight-status-backend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  frontend:
    runs-on: ubuntu-latest
    needs: version
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Angular Build
      run: cd flightstatus-frontend && npm install -g @angular/cli && npm install && ng build
   
    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/jfwenisch/flightstatus-frontend

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: flightstatus-frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  release:
    runs-on: ubuntu-latest
    needs:  [backend, frontend]
    steps:
    - uses: actions/checkout@v3
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{needs.version.outputs.tag}}
        name: Release ${{needs.version.outputs.tag}}
        body: ${{needs.version.outputs.changelog}}
