# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: cd flight-status-backend && mvn -B package --file pom.xml
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 16
        # you can set branches for semantic-release above v16.
        branches: |    
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'master', 
            'main', 
            {
              name: 'develop', 
              prerelease: true
            }, 
            {
              name: 'feature/CI', 
              prerelease: true
            }, 
            {
              name: 'main', 
              prerelease: false
            }
          ]
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
